### ISSUE TITLE
script failed error

### ISSUE THREAD

**Issue by dancer69** [dersphere/plugin.video.trakt_list_manager#3]
Trying to run the plugin and I always get script failed error. Here is the log:
=================================================================
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named xbmcswift2
                                            Traceback (most recent call last):
                                              File "C:\Users\.......\plugin.video.trakt_list_manager\addon.py", line 20, in <module>
                                                from xbmcswift2 import Plugin, xbmc, xbmcgui
                                            ImportError: No module named xbmcswift2
                                            -->End of Python script error report<--
===================================================================

I'm using Gotham version.
The module xbmcswift is already on xbmc' s addons folder with name "script.module.xbmcswift2"
I've already posted on xbmc's forum thread but after 3 days I get no answer.

**Comment by dersphere** [comment]
Should be fixed in Helix
