### ISSUE TITLE
New endpoint for trakt api

### ISSUE THREAD

**Issue by tknorris** [dersphere/plugin.video.trakt_list_manager#5]
A few days ago trakt introduced a new end point for users of their V2 API. The old end point is "api.trakt.tv" the new one is "api-v2launch.trakt.tv" The new one has dedicated servers and doesn't run the old demanding V1 API so it's much more reliable. You might want to change it before you push a release for this addon.

**Comment by dersphere** [comment]
Thanks, I will change it before the release.
What about the APIKey (or client id), is it in use in any other add-on/library?

**Comment by tknorris** [comment]
Nope, I requested a new one specifically for this addon. You can request a new one if you want, or I can check to see if Jusin can transfer it to your id if you want. If you request a new one, be sure to request media center auth as the default is to only support oauth.

**Comment by dersphere** [comment]
I am fine with the current (new) one when it is not used for "other add-ons" ;-)

Thanks again, I didn't have much time recently for open source stuff.
